### ISSUE TITLE
oracle_linux_image_name update required.

### ISSUE THREAD

**Issue by heungheung** [hyder/ocigitlab#12]
You probably will hit the image not found problem. Recommend you update the image name to the latest one:
- oracle_linux_image_name = "Oracle-Linux-7.4-2018.01.20-0"
https://docs.us-phoenix-1.oraclecloud.com/Content/Resources/Assets/OracleProvidedImageOCIDs.pdf

or just put the info in README.md

**Comment by hyder** [comment]
Fixed. You can check.
